### PR TITLE
New torrent search provider hdaccess.net

### PR DESCRIPTION
**Pull request by jonnyboy**
New torrent search provider hdaccess.net

### CODE REVIEW

**Comment by jonnyboy** [comment]
Considering I copied almost all of mine from those already here, I do not see why not.

**Comment by RuudBurger** [comment]
I need an invite for testing also ;)

**Comment by jonnyboy** [comment]
Invite sent. Thanks

**Comment by jonnyboy** [comment]
Is this going to be merged?

**Comment by RuudBurger** [comment]
Sorry for the wait. Expecting my first kid, not much time the last few weeks.
I've merged it, but removed the "favor" part as that should be covered by the prefered words etc.

**Comment by jonnyboy** [comment]
Congrats on your first kid, hope your wife is doing fine.

Thanks

**Pull request merged**
