### PR TITLE
update trakt.tv after download and not snatch

### PR DESCRIPTION
**Pull request by MikeBuzz**

### CODE REVIEW

**Comment by fernandog** [comment]
@MikeBuzz @RuudBurger shouldn't this be an option? Will this work if user don't use the renamer?

from PR: "renamer.after"

**Comment by peerster** [comment]
+1 for worrying that it now requires renamer function to work.

**Comment by MikeBuzz** [comment]
at the moment it will only work on rename, as per the rest of the notifyers, just checking most of them have an advance option to notify on snatch, i will see if i can work out how to all add this to trakt,

**Comment by fernandog** [comment]
@MikeBuzz why not keep the old behavior as an option? (snatch or download)

**Comment by MikeBuzz** [comment]
@fernandog the issue with the old behavior is that if a movie is snatched but the download does not complete for any reason the movie is still added to your collection. if i can work out how to have both options i will add this, its is possible as the others have on snatch as an advance option just need to get my head round how its working

**Comment by fernandog** [comment]
@MikeBuzz ok I see. never mind them

**Pull request merged**
