### PR TITLE
update kickass domain address

### PR DESCRIPTION
**Pull request by yoyos**
Add the new kickass domain and remove older ones

### CODE REVIEW

**Comment by wlossw** [comment]
Kickass is down. The mirror listed kickass.cd is not a true KAT mirror.

**Comment by matmuilwijk** [comment]
Like said before: There are no official KickAss domains left. And, mirrors only have the old magnets available, so new stuff won't be added...

Would be nice to see some of Torrentz resurfacing mirrors in CP though... Some of them have access to 23 sites' meta...

**Comment by yoyos** [comment]
I'm sorry but I found new releases on kickass.cd, that's why I thought it was their new website.

**Comment by matmuilwijk** [comment]
Probably a KAT lookalike that uses TPB's api or something.

Guess we'll have to face the fact that we lost 2 Giants in one week...

**Comment by wlossw** [comment]
According to TorrentFreak, it's a TPB mirror. I heard the team from KAT is working on a new site, so I'm sure we will get it when it's up. That being said, we do need more open trackers, as nothing seems to be working very well ATM. I may have to switch to a paid Usenet solution if thinks keep going this way.

**Comment by matmuilwijk** [comment]
Totally agreed... TPB only returns fake movies (You know, from those releasegroups that only do TV series, etc...) and the rest (rarbg) won't return anything...

Maybe I'll try to add the new YTS to the mix, but doubt it will be usefull...

**Comment by wlossw** [comment]
what about 1337x.to

**Comment by matmuilwijk** [comment]
Haven't checked it yet... Easy way to do it?

**Comment by wlossw** [comment]
I'm no coder, So I can;t speak to the ease of integration. That being said, It is a decent public tracker for movies and tv shows.

**Comment by matmuilwijk** [comment]
I'm just learning basic python, but sounds like a task that shouldnt be that hard...

**Comment by ward0** [comment]
@matmuilwijk  sickrage doesn't suppor 1337 , so i doubt they don't have search able website by code..

**Comment by yoyos** [comment]
It seems https://extratorrent.cc/ gives pretty good results

**Comment by OmgImAlexis** [comment]
@yoyos this can be closed since kickass doesn't exist anymore.

**Review by seanboothm — APPROVED** [review]

**Comment by noingwhat** [comment]
kickass.cd is currently back up and running

**Comment by OmgImAlexis** [comment]
kickass.cd isn't the real one and shouldn't be added as users won't know that it's not the real one.

**Review by OmgImAlexis — CHANGES_REQUESTED** [review]
This needs closed as Kickass is gone.

**Comment by ward0** [comment]
@RuudBurger , @OmgImAlexis  
can we add extratorrent pls?

https://github.com/SickRage/SickRage/blob/master/sickbeard/providers/extratorrent.py

**Comment by diego-vieira** [comment]
http://kickasstorrents.to/

**Comment by OmgImAlexis** [comment]
@diego-vieira that isn't the real kat.

**Comment by yoyos** [comment]
This one is: https://katcr.co/new/

**Comment by OmgImAlexis** [comment]
@yoyos yep that's it. https://github.com/SickRage/SickRage/issues/2869

**Comment by muhahacz** [comment]
https://katcr.co/new/ is new one.

http://torrentproject.se/
https://1337x.to/
http://extratorrent.cc/
https://isohunt.to

**Comment by matmuilwijk** [comment]
Question is, do they still support the api of the old KA...

Op 28 jan. 2017 18:22 schreef "Lukas M" <notifications@github.com>:

**Comment by muhahacz** [comment]
There is NMP api/wrapper (https://github.com/JimmyLaurent/torrent-search-api/blob/master/lib/providers/torrentz2.js) for torrentz2.eu, which indexing zooqle, extratorrent, 1337 , isohunt,  torrentproject.se and many more (https://torrentz2.eu/help#indexed), unfortunatelly katcr.co/new/ is not on the list YET.

You can get torrent just like that:
https://torrentz2.eu/search?f=gattaca
https://torrentz2.eu/3b33bc5dc0eb29150a55d4eaab0e6ee7b201efea
magnet:?xt=urn:btih:3b33bc5dc0eb29150a55d4eaab0e6ee7b201efea',
http://itorrents.org/torrent/3b33bc5dc0eb29150a55d4eaab0e6ee7b201efea.torrent

Maybe we can use this, it should be more consistent instead of obsolete trackers in couchpotato right now.

**Pull request closed without merging**
