### PR TITLE
Fixed style bug causing top part of the directory list modal to be hi…

### PR DESCRIPTION
**Pull request by geo242**
### Description of what this fixes:
Fixes style bug causing top part of the directory list modal to be hidden and not near the field it originated from

### CODE REVIEW

**Comment by jrochet** [comment]
I can't wait for this to merge into master.  Py27 only helps for the "from" directory selector, the "to" directory selector is hidden under the address bar of the browser.

**Comment by danepowell** [comment]
Thanks a lot. I was experiencing the same bug, can confirm this fixes it.

**Comment by allkindsofralph** [comment]
this is still happening to me. Anyone know if or when this will merge into master?

**Comment by dannygale** [comment]
I have this issue on chrome but not safari

**Comment by jrochet** [comment]
I forget where it is but the interface shows (or maybe the wiki) that they don't want to hear about this issue and if they do they will hurt cats.  I'd say don't hold your breath and just edit settings.conf manually instead.  In Windows that is at c:\windows\system32\config\systemprofile\appdata\<forget which one>\couchpotato\settings.cong

**Comment by underchemist** [comment]
why wouldn't you want to address a UI fix to make your software more usable?

**Comment by jrochet** [comment]
I was referring to this from the main readme.md:
"Running from Source
CouchPotatoServer can be run from source. This will use git as updater, so make sure that is installed.

Windows, see the CP forum for more details:

Install Python 2.7
Then install PyWin32 2.7 and GIT
If you come and ask on the forums 'why directory selection no work?', I will kill a kitten, also this is because you need PyWin32"

I may be mistaken that we're on the same topic, though I'm fairly certain.  The issue had been raised many times and the best I've seen is a trick in Chrome developer tools where you manually change the CSS while browsing CP's settings page to make it show the full directory selection pane.  You might find that solution by searching the issues section including closed ones.

**Comment by lance36** [comment]
please fix, i cannot set my library to other disks other than C:

image
i've copy\pasting into the "textbox" invain.

image

**Comment by allkindsofralph** [comment]
I just submitted a fix for this by changing the CSS file. It helped me on my computer

If you want to do it yourself until/if it is merged then just edit this file: 

**couchpotato/static/style/combined.min.css**

scroll to the bottom and find line 987

.directory_list{z-index:2;position:absolute;width:450px;margin:28px 0 20px;background:#ac0000;box-shadow:0 0 15px 2px rgba(0,0,0,.15);border-radius:3px 3px 0 0}

paste this line in replacement

.directory_list{z-index:2;position:absolute;top:60px;width:450px;margin:28px 0 20px;background:#ac0000;box-shadow:0 0 15px 2px rgba(0,0,0,.15);border-radius:3px 3px 0 0}

**Comment by jrochet** [comment]
@allkindsofralph Great job! Just added the top:60px; and restarted my CP Windows service and it works perfectly.  Thanks!

**Comment by allkindsofralph** [comment]
no problem! it was bugging me for quite a while as well.

**Comment by AMNegron** [comment]
Just installed 3.0.1, and this bug is still present. Will attempt @allkindsofralph 's suggestion later today.
screenshot 1

**Comment by kamikaze2112** [comment]
> I just submitted a fix for this by changing the CSS file. It helped me on my computer
> 
> If you want to do it yourself until/if it is merged then just edit this file:
> 
> **couchpotato/static/style/combined.min.css**
> 
> scroll to the bottom and find line 987
> 
> .directory_list{z-index:2;position:absolute;width:450px;margin:28px 0 20px;background:#ac0000;box-shadow:0 0 15px 2px rgba(0,0,0,.15);border-radius:3px 3px 0 0}
> 
> paste this line in replacement
> 
> .directory_list{z-index:2;position:absolute;top:60px;width:450px;margin:28px 0 20px;background:#ac0000;box-shadow:0 0 15px 2px rgba(0,0,0,.15);border-radius:3px 3px 0 0}

This worked like a charm.  Updated that css file, restarted CP from within the web interface, and closed/reopened the web interface and it was fixed.

**Comment by allkindsofralph** [comment]
@RuudBurger merge?

**Comment by kamikaze2112** [comment]
How is this still an issue? Been almost a year and every time I have to update CP or spin up a new instance I have to fix this by hand.

**Pull request closed without merging**
