### PR TITLE
New torrent tracker HD4Free.xyz

### PR DESCRIPTION
**Pull request by jonnyboy**
New torrent search provider.

### CODE REVIEW

**Comment by jonnyboy** [comment]
Can you give me an example? I have been using this for a couple of months.

**Comment by jonnyboy** [comment]
I am attaching the log of my attempt, works fine for me. Show me your log, so I can dig into it, please.

08-21 12:58:16INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/furious/?limit=5, data: []
08-21 12:58:16INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=ngram&query=furious, data: []
08-21 12:58:16INFO[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=&t=furious, data: []
08-21 12:58:17INFO[ie.providers.info.omdbapi] Found: Furious (2011)
08-21 12:58:17INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/168259?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:18INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/167104?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:18INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/337339?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:19INFO[providers.info.themoviedb] Found: [u'Furious 7 (2015)', u'Furious (1984)', u'Fast & Furious 8 (2017)']
08-21 12:58:19INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/furious+7/?limit=5, data: []
08-21 12:58:19INFO[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=&t=furious+7, data: []
08-21 12:58:19INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=ngram&query=furious+7, data: []
08-21 12:58:19INFO[ie.providers.info.omdbapi] Found: Furious 7 High Octane (2015)
08-21 12:58:19INFO[providers.info.themoviedb] Found: [u'Furious 7 (2015)']
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt2820852/?adding=1, data: []
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt2820852/, data: []
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2820852, data: []
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/tt2820852?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:29INFO[ie.providers.info.omdbapi] Found: Furious Seven (2015)
08-21 12:58:29INFO[ie.providers.info.omdbapi] Found: Furious Seven (2015)
08-21 12:58:29INFO[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/w154/dCgm7efXDmiABSdWDHBDBx2jwmn.jpg, data: []
08-21 12:58:29INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt2820852/, data: []
08-21 12:58:30INFO[core.media.movie.searcher] Search for Furious 7 in 1080p ignoring ETA
08-21 12:58:30INFO[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=xxx&username=xxx&imdbid=tt2820852&internal=False, data: []
08-21 12:58:31INFO[edia._base.providers.base] Found: score(358) on HD4Free: Furious Seven 2015 EXTENDED 1080p BluRay DTS-HD MA 7 1 x264-LEGi0N (2015)  none  2015  x264  18 seeders Internal
08-21 12:58:31INFO[edia._base.providers.base] Found: score(197) on HD4Free: Fast and Furious 7 2015 BluRay 1080p DTS x264-MTeam (2015)  none  2015  x264  1 seeders
08-21 12:58:33INFO[edia._base.providers.base] Found: score(425) on HD4Free: Furious 7 2015 BluRay 1080p DTS x264-LEGi0N (2015)  none  2015  x264  3 seeders Internal
08-21 12:58:33INFO[edia._base.providers.base] Found: score(84) on HD4Free: Furious Seven 2015 EXTENDED 1080p BluRay DTS-HD MA 7 1 x264-SiMPLE (2015)  none  2015  x264  4 seeders
08-21 12:58:34INFO[edia._base.providers.base] Found: score(198) on HD4Free: Fast and Furious 7 2015 Extended 1080p BluRay DTS-HD MA 7 1 X264 DiRTYBURGER (2015)  none  2015  x264  0 seeders Internal
08-21 12:58:35INFO[tato.core.plugins.release] Ignored, not enough seeders, has 0 needs 1: Fast and Furious 7 2015 Extended 1080p BluRay DTS-HD MA 7 1 X264 DiRTYBURGER (2015)  none  2015  x264  0 seeders Internal
08-21 12:58:35INFO[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/download.php?torrent=10818&torrent_pass=e09fa278eff7e42f2e654a666c9c638a, data: []
08-21 12:58:35INFO[ore.downloaders.blackhole] Downloading torrent to C:\Users\jonnyboy\Downloads\torrents\Furious 7 2015 BluRay 1080p DTS x264-LEGi0N (2015) none 2015 x264 3 seeders Internal.torrent.
08-21 12:58:35INFO[tato.core.plugins.release] Snatched "Furious 7 2015 BluRay 1080p DTS x264-LEGi0N (2015)  none  2015  x264  3 seeders Internal": Furious 7 (2015) in 1080p
08-21 12:58:36INFO[tato.core.plugins.release] Renamer disabled, marking media as finished: Furious 7 (2015) in 1080p

**Comment by jonnyboy** [comment]
Here is the log of latest run, no issues. Please post your log so I can dig into it.

Thanks

08-21 12:58:16INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/furious/?limit=5, data: []
08-21 12:58:16INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=ngram&query=furious, data: []
08-21 12:58:16INFO[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=&t=furious, data: []
08-21 12:58:17INFO[ie.providers.info.omdbapi] Found: Furious (2011)
08-21 12:58:17INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/168259?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:18INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/167104?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:18INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/337339?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:19INFO[providers.info.themoviedb] Found: [u'Furious 7 (2015)', u'Furious (1984)', u'Fast & Furious 8 (2017)']
08-21 12:58:19INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/furious+7/?limit=5, data: []
08-21 12:58:19INFO[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=&t=furious+7, data: []
08-21 12:58:19INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=ngram&query=furious+7, data: []
08-21 12:58:19INFO[ie.providers.info.omdbapi] Found: Furious 7 High Octane (2015)
08-21 12:58:19INFO[providers.info.themoviedb] Found: [u'Furious 7 (2015)']
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt2820852/?adding=1, data: []
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt2820852/, data: []
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2820852, data: []
08-21 12:58:28INFO[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/tt2820852?api_key=xxx&append_to_response=alternative_titles, data: []
08-21 12:58:29INFO[ie.providers.info.omdbapi] Found: Furious Seven (2015)
08-21 12:58:29INFO[ie.providers.info.omdbapi] Found: Furious Seven (2015)
08-21 12:58:29INFO[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/w154/dCgm7efXDmiABSdWDHBDBx2jwmn.jpg, data: []
08-21 12:58:29INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt2820852/, data: []
08-21 12:58:30INFO[core.media.movie.searcher] Search for Furious 7 in 1080p ignoring ETA
08-21 12:58:30INFO[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=xxx&username=xxx&imdbid=tt2820852&internal=False, data: []
08-21 12:58:31INFO[edia._base.providers.base] Found: score(358) on HD4Free: Furious Seven 2015 EXTENDED 1080p BluRay DTS-HD MA 7 1 x264-LEGi0N (2015)  none  2015  x264  18 seeders Internal
08-21 12:58:31INFO[edia._base.providers.base] Found: score(197) on HD4Free: Fast and Furious 7 2015 BluRay 1080p DTS x264-MTeam (2015)  none  2015  x264  1 seeders
08-21 12:58:33INFO[edia._base.providers.base] Found: score(425) on HD4Free: Furious 7 2015 BluRay 1080p DTS x264-LEGi0N (2015)  none  2015  x264  3 seeders Internal
08-21 12:58:33INFO[edia._base.providers.base] Found: score(84) on HD4Free: Furious Seven 2015 EXTENDED 1080p BluRay DTS-HD MA 7 1 x264-SiMPLE (2015)  none  2015  x264  4 seeders
08-21 12:58:34INFO[edia._base.providers.base] Found: score(198) on HD4Free: Fast and Furious 7 2015 Extended 1080p BluRay DTS-HD MA 7 1 X264 DiRTYBURGER (2015)  none  2015  x264  0 seeders Internal
08-21 12:58:35INFO[tato.core.plugins.release] Ignored, not enough seeders, has 0 needs 1: Fast and Furious 7 2015 Extended 1080p BluRay DTS-HD MA 7 1 X264 DiRTYBURGER (2015)  none  2015  x264  0 seeders Internal
08-21 12:58:35INFO[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/download.php?torrent=10818&torrent_pass=<torrent_pass>, data: []
08-21 12:58:35INFO[ore.downloaders.blackhole] Downloading torrent to C:\Users\jonnyboy\Downloads\torrents\Furious 7 2015 BluRay 1080p DTS x264-LEGi0N (2015) none 2015 x264 3 seeders Internal.torrent.
08-21 12:58:35INFO[tato.core.plugins.release] Snatched "Furious 7 2015 BluRay 1080p DTS x264-LEGi0N (2015)  none  2015  x264  3 seeders Internal": Furious 7 (2015) in 1080p
08-21 12:58:36INFO[tato.core.plugins.release] Renamer disabled, marking media as finished: Furious 7 (2015) in 1080p

**Comment by jonnyboy** [comment]
Hey @RuudBurger,

When you have a spare minute, could you tell me what I need to get this pull request merged?

Thanks

**Comment by RuudBurger** [comment]
I didn't merge because someone reported it didn't work. Looks fine though.
Sorry for the delay

**Comment by jonnyboy** [comment]
thank you

**Pull request merged**
