### PR TITLE
Fix renamer on systems, which use UTF-8 as default encoding

### LINKED ISSUE #4449: Plugin Renamer failing with special characters such as é è à
### Information:
Movie(s) I have this with: Any movie with characters such as é è à in the name (french movies), the renamer plugin fails
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 2f5526d5 (2015-01-02 18:54:36)
Running on: Synology

### Logs:
```
01-04 09:22:34 ERROR [tato.core.plugins.renamer] Failed renaming the file "Paris A Tout Prix 2013 FRENCH 720p BluRay x264-NERDHD.mkv" : Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume1/Videos/Movies/Paris \xc3\xa0 tout prix (2013)/Paris \xc3\xa0 tout prix (2013).mkv' 
```

### PR DESCRIPTION
**Pull request by Dam4rusxp**
This fixes #4449.
This is not the prettiest fix, but it works. I would advice, to rework the internals towards using unicode wherever it's possible and just encode to sys.getfilesystemencoding() when it's really necessary. I can't think of a modern system, that doesn't understand UTF-8 anyway...

### CODE REVIEW

**Comment by tonybeccar** [comment]
Hello!
Is it possible to merge this fix into the master branch? That way we can update. I'm using openelec so I cannot do this manually... I am having lots of trouble with french and spanish movies... thanks!!

**Comment by RuudBurger** [comment]
With what files can I test this?

**Comment by Dam4rusxp** [comment]
I tested my changes by importing a movie with foreign characters in the title (e.g. tt3954222), by letting it copy, link and move.

**Comment by chtk** [comment]
Some other titles the renamer fails on, are:
* [\[Rec\]²](http://www.imdb.com/title/tt1245112)
* [\[Rec\]³: Génesis](http://www.imdb.com/title/tt1649444)

**Comment by gitsf** [comment]
I changed these five files and tried running the renamer against The Lion King 1 1/2. It did not change the outcome for me.
system: Synology DSM 5.2-5592 Update 3
Log output: http://pastebin.com/raw.php?i=viA8vSb2

**Comment by Steggl** [comment]
Would this fix German Umlauts, too?

**Pull request closed without merging**
