### PR TITLE
Update Trakt automation to v2 API

### PR DESCRIPTION
**Pull request by alias1**
Updated the trakt api to utilise the new v2 endpoints/auth/etc.

http://docs.trakt.apiary.io/#reference/authentication-pin
http://docs.trakt.apiary.io/#reference/sync/get-watchlist/get-watchlist

### CODE REVIEW

**Comment by RuudBurger** [comment]
Thanks!

**Comment by alias1** [comment]
Np :)



—

**Comment by gotson** [comment]
Hi @alias1 , i tried using this, but i cannot generate a token from a PIN. On top of it, it seems that tokens will only be valid ofr 3 months, then need to be refreshed.

Is there a way to use the generated PIN instead of the token, and never have to renew ?

**Comment by alias1** [comment]
Technically it's a little hacky atm as I'm not sure how/if you can make the API call from CP and store/refresh the token from that and/or setup a callback for the oauth flow.




It will work if you manually exchange the pin through an API call though.




The proper/best case way to support this is to have the ability to do a proper oauth flow in CP, and for it to be able to make the appropriate refresh call as required.



—

**Pull request merged**
