### PR TITLE
Added button to remove files when deleting media

### PR DESCRIPTION
**Pull request by wolph**

### CODE REVIEW

**Comment by RuudBurger** [comment]
Sorry for my late response.
I feel this needs a lot of testing and checking for security issues and faulty loops etc. I don't want this to be responsible for removing stuff that aren't movies ;)

**Comment by WoLpH** [comment]
We can always add a huge disclaimer to the delete button ;)

Better solution might be to list the files that are going to be deleted but
that's a bit out of my scope.

**Comment by xenithorb** [comment]
What happened to this? I started deleting things thinking that it would remove them from the filesystem, and then figured maybe I had filesystem permissions wrong, spent a bunch of time tailing logs and trying to troubleshoot what I assumed was the functionality of the word "delete" (I mean really, come on)  

Where is this feature? Seems like you've been going back and forth on this for 2 years or so...

**Comment by blade316** [comment]
+1

**Comment by piotrasd** [comment]
+1

**Comment by BDeveau** [comment]
+1

**Comment by GamerGun** [comment]
+1

**Pull request closed without merging**
