### PR TITLE
OMDBAPI was not working without an API key

### PR DESCRIPTION
**Pull request by jmseaton**
Based off of TMDB provider.  Will require a section in settings.conf

[omdbapi]
api_key =

### Description of what this fixes:

OMDBAPI requires and API key, and was not working.  An API key for OMDB requires a donation/becoming a "patron".
i.e.
 `06-09 14:45:48 ERROR [hpotato.core.plugins.base] Failed opening url in OMDBAPI: http://www.omdbapi.com/?type=movie&i=tt6003368 Traceback (most recent call last):

HTTPError: 401 Client Error: Unauthorized for url: http://www.omdbapi.com/?type=movie&i=tt6003368`

### CODE REVIEW

**Comment by jmseaton** [comment]
The settings.conf that gets created would need to have a blank value as a default.  I can't seem to locate where it's created.

**Comment by clinton-hall** [comment]
to add settings... at the bottom of the file, add
```
config = [{
    'name': 'OMDB',
    'description': 'apikey for OMDB',
    'tab': 'general',
    'options': [
            {
                'name': 'omdb_api',
                'default': '',
                'description': ('Become a Patron <a href="https://www.patreon.com" target="_blank">here</a>  to get your key.'), 
             },
    ],
}]
```
I haven't tested... you might need to tweak to get this on the right tab etc...

look at examples at https://github.com/CouchPotato/CouchPotatoServer/blob/master/couchpotato/core/plugins/renamer.py#L1358

I'll talk to Ruud to see if we can get this merged as this is a big ticket fix ;)

**Comment by RuudBurger** [comment]
Fixing this now, the response also did change. So even if adding the key, it wouldn't use any data from omdb..

**Comment by RuudBurger** [comment]
Should be fixed now. Thanks for the PR!

**Comment by markat2k** [comment]
Hi, I can't seem to find a way to report an issue, so I'm commenting on this, hoping you will see it Mr RB.

I found this error in my log file, debug enabled;

ERROR [   couchpotato.core.event] Error in event "movie.info", that wasn't caught: Traceback (most recent call last):
  File "/opt/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/opt/CouchPotatoServer/couchpotato/core/media/movie/providers/info/omdbapi.py", line 62, in getInfo
    cached = self.getCache(cache_key, self.urls['info'] % identifier, timeout = 3, headers = {'User-Agent': Env.getIdentifier()})
TypeError: not enough arguments for format string
encoding=UTF-8 debug=True args=[] app_dir=/opt/CouchPotatoServer data_dir=/home/user/.couchpotato desktop=None options=Namespace(config_file='/home/user/.couchpotato/settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='/home/user/.couchpotato/couchpotato.pid', quiet=False)

I think there may be two issues in this code, I hope this makes sense;

One;

20    urls = {
21        'search': 'https://www.omdbapi.com/?apikey=%s&type=movie&%s',
22        'info': 'https://www.omdbapi.com/?apikiey=%s&type=movie&i=%s',
23    }

==>

20    urls = {
21        'search': 'https://www.omdbapi.com/?apikey=%s&type=movie&%s',
22        'info': 'https://www.omdbapi.com/?apikey=%s&type=movie&i=%s',
23    }

Two;

62        cached = self.getCache(cache_key, self.urls['info'] % identifier, timeout = 3, headers = {'User-Agent': Env.getIdentifier()})

==>

62        cached = self.getCache(cache_key, self.urls['info'] % (self.getApiKey(), identifier), timeout = 3, headers = {'User-Agent': Env.getIdentifier()})

**Comment by fabriziobertoglio1987** [comment]
@RuudBurger 

> Should be fixed now. Thanks for the PR!

I am on 3.0.1 and I have this error in my logs

how can I include the api key in my settings?  Thanks

```
 Failed opening url in OMDBAPI: http://www.omdbapi.com/?type=movie&i=tt3300542 Traceback (most recent call last):
ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))
```

**Comment by tm9k1** [comment]
hi, sorry for necro-posting..

how can I include the api key in my settings?

**Comment by clinton-hall** [comment]
you need to manually edit the settings.conf

```
[omdbapi]
api_key = xxxxxxx
```
note, there is already an apikey entered for CP to use, but you can add your own.

**Comment by tm9k1** [comment]
cool! thanks for the reply

**Pull request closed without merging**
