### PR TITLE
add custom tags for omgwtfnzbs

### PR DESCRIPTION
**Pull request by desmoloch**
New option for omgwtfnzbs to add custom tags, like custom tags for newznab.
Now its possible to add catid´s (or any other parameters) via settings, for example catid=18 for foreign movies

### CODE REVIEW

**Comment by RuudBurger** [comment]
Thanks!

**Comment by lolost** [comment]
is the fix is available ? how can I access to it ? don't see option under omg section...
thanks

**Comment by RuudBurger** [comment]
It's in develop for now

**Comment by lolost** [comment]
is there any news on this post ? do you have an idea of when the fix will be available ? 1 day ? 1 week ? 1 month ? ;)
thanks

**Pull request merged**
