### PR TITLE
Fix magnet links from Jackett

### PR DESCRIPTION
**Pull request by mrlt8**
### Description of what this fixes:

1. Attempts to fix the "InvalidSchema: No connection adapters were found for" magnet links from Jackett.
2. Attempts to fix the issue of magnet links not being recognized due to being embedded in 302 redirected urls.

### Related issues:

https://github.com/Jackett/Jackett/issues/8788

### CODE REVIEW

**Comment by faebser** [comment]
Would it be possible to merge this pull request?

**Comment by JohnBernardsson** [comment]
Would love this to be fixed... Or at least some manual workaround to be posted. I understand the issue, but I don't know if it's possible to manually instruct Couchpotato to take some magnet link...

**Comment by faebser** [comment]
@JohnBernardsson I can confirm that the changes in this pull request work. You can add these changes to your installation of couchpotato manually, which I did.

**Comment by JohnBernardsson** [comment]
hey @faebser thanks for the quick response and sorry for my late one :P

I just added the changes to the py files, but after that, still getting this error 🤔:

[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 210, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/base.py", line 221, in urlopen response = r.request(method, url, **kwargs) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 469, in request resp = self.send(prep, **send_kwargs) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 598, in send history = [resp for resp in gen] if allow_redirects else [] File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 194, in resolve_redirects **adapter_kwargs File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 571, in send adapter = self.get_adapter(url=request.url) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 645, in get_adapter raise InvalidSchema("No connection adapters were found for '%s'" % url) InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:62578f18cc13acb4cec773b96f299fdc8594cafa&dn=The.Lighthouse.2019.1080p.Bluray.DTS-HD.MA.5.1.X264-EVO%5BTGx%5D&xl=12324259140&tr=udp%3A%2F%2Ftracker.coppersurfer.tk:6969/announce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org:6969/announce&tr=udp%3A%2F%2Fopen.stealth.si:80/announce&tr=udp%3A%2F%2Fexodus.desync.com:6969&tr=udp%3A%2F%2Fp4p.arenabg.com:1337/announce&tr=udp%3A%2F%2Fexplodie.org:6969/announce&tr=udp%3A%2F%2Ftracker.opentrackr.org:1337/announce&tr=udp%3A%2F%2Ftracker.tiny-vps.com:6969/announce&tr=udp%3A%2F%2Fopen.demonii.si:1337/announce&tr=udp%3A%2F%2Ftracker.torrent.eu.org:451/announce&tr=udp%3A%2F%2Ftracker.pirateparty.gr:6969/announce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu:80/announce&tr=udp%3A%2F%2Ftracker.cyberia.is:696


Not sure if I am missing something... I am working with a Synology Nas, and the Couchpotato version from the Synocommunity, maybe that's the thing...

**Comment by mrlt8** [comment]
@JohnBernardsson looks like the patch didn’t go through.. Did you restart couchpotao to make the changes go into effect?

**Comment by JohnBernardsson** [comment]
@mrlt8 @faebser 
Well, maybe I did something wrong the other day (I stopped Couchpotato, did the changes, and then restarted Couchpotato...), or I am not sure, but today, out of curiosity, I tested and it worked! :)

Thanks a lot!

**Comment by pando85** [comment]
up! It could be interested to merge it

**Comment by drvenabili** [comment]
Paging @RuudBurger as they're the ones who made the latest commits on this repo: merging this would be brilliant

**Pull request closed without merging**
