### PR TITLE
Fix bug in IMDB watchlist loader

### PR DESCRIPTION
**Pull request by iasmanis**
### Description of what this fixes:
Watchlist loader gets in endless loop loading list of more than 320 items

### Related issues:
None

### CODE REVIEW

**Comment by dacabdi** [comment]
@iasmanis IMDB's interface changed slightly, as of now the list is lazy loaded at a pace of a 100 items at a time. The scrapper is incapable to passing pages. I have a list with about ~3k films. I found a workaround by changing the HTTP query to use the key `page` and iterate through. However, watchlists, located by user id, do not allow this, you would need the actual list's URL. Could not find any other solution. Let me know if you want to incorporate my source to this.

**Comment by shtrom** [comment]
I just tried this PR on top of the current develop, and it did fix my issue straight away. CouchPotato went from using 100% CPU to almost nothing (200+ titles in watchlist), and I suspect it also stopped queueing duplicates of the same titles.

@RuudBurger I think this should be merged soon.

**Comment by shtrom** [comment]
(Though, maybe all the whitespace changes should be separated or removed, first).

**Comment by shtrom** [comment]
@RuudBurger is there something I could do to help push this PR along?

It was working fine for me before, but I realised that I was no longer on `master` and therefore not getting upgrades. I just pulled latest `master`, and noticed that the bug was still present, then cherry-picked commit 1303955874cae38e601f3b4a88a580973e538787 on top, and this fixed the high CPU load as before.

**Pull request closed without merging**
