### PR TITLE
When I try to change the renamer to or from folder locations..

### PR DESCRIPTION
**Pull request by nydave69**
### Description of what this fixes:
...

### Related issues:
...
image

### CODE REVIEW

**Comment by RuudBurger** [comment]
Please make sure to make the PR to develop.

**Comment by nydave69** [comment]
I also found an issue when you go to update the managed folders

image

It keeps adding \ to the path names

If you check the config file itself you get;

image


and with every edit attempt..
Oh and the edit overlay has the same issues..

**Comment by nydave69** [comment]
any fix to these issues anytime soon????

**Comment by nydave69** [comment]
is there a way to clean up the database.
the managed movies count keeps climbing with every scan..

image

**Comment by nydave69** [comment]
Lately the renamer seems to have developed a bug...
this is what the episode name is set to....
<thename> (<year>)  (<imdb_id>) (<quality>-<video> <audio>-<audio_channels>) (<cd>).<ext>

example outputs;
Toto the Hero (1991) (tt0103105) (1080p-avc1- ().mp4
Max Winslow and The House of Secrets (2020) (tt8896632) (1080p-H264-) ().mkv

Attempt to clean up double separaters due to missing data for fields.     is also checked but that never seemed to work..
I always end up with the () at the end of the file name and have to remove it..

But the video and audio media info being what it is something new..
And sometimes it has some really weird things listed...

**Comment by nydave69** [comment]
I take it that this project is dead....

**Pull request closed without merging**
