### PR TITLE
Initial support for Plex Media Server w/Plex Home

### PR DESCRIPTION
**Pull request by mannkind**
Based on #4328 and fixes #4239, but supports fetching the authentication token using username/password while still being able to use just an auth token if you want.

### CODE REVIEW

**Comment by RuudBurger** [comment]
What is the client-identifier and why is it set to `b3a6b24dcab2224bdb101fc6aa08ea5e2f3147d6`?

**Comment by mannkind** [comment]
The Client-Identifier is what uniquely identifies a "device" associated for a given Plex Media Server. b3a6b24dcab2224bdb101fc6aa08ea5e2f3147d6 is just the sha1 hash of the words "CouchPotato Notifier"

**Comment by Ockingshay** [comment]
Has this been implemented yet? Pretty crucial for all Plex users, which i bet is quite a large % of CP users.

**Comment by Ockingshay** [comment]
and this is a guide on how to find one's auth token: https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token

**Comment by chuckkay** [comment]
mannkind, 
couldn't wait for merge so manually installed you fix works great thanks...

Question: can you take a look at fixing something else with plex server notification...

It seams CouchPotato is telling Plex to update all Video Related Libraries... including My Home Videos (of which i have a lot) this makes each update take too long.. Fortunatly plex is not refreshing TV Library on every couch potato notification...


I have 3 Video Related Library's  
My Movies 
My Kids Movies
Home Videos
on couchpotato notification Plex is refreshing all three...

even though Couchpotato only uses two directories for categories and renaming settings
(My Movies & My Kids Movies)

any chance of a fix... or even better, instead of rescanning the whole, could it just update a specific movie or path....

**Comment by weezywee** [comment]
@Developers - Is this going to be merged?
@Anyone - How do I merge this with my local copy until it is officially merged?

**Comment by valeriomazzeo** [comment]
+1 we do want this!

**Comment by mannkind** [comment]
@weezywee - I followed [github's documentation](https://help.github.com/articles/checking-out-pull-requests-locally/) to pull in the change locally.

I really hope support for Plex Home gets merged soon, even if it's not my pull request.

**Comment by weezywee** [comment]
@mannkind - Thank you!

**Comment by Ockingshay** [comment]
sickbeard have now also implemented this: https://github.com/midgetspy/Sick-Beard/pull/890#issuecomment-72387150

Hopefully that helps for a fix in CP?

**Comment by jwillmer** [comment]
push!

**Comment by RuudBurger** [comment]
Sorry for the slowness guys. Getting ready for my first kid. Not much time right now ;)

**Pull request merged**
