### PR TITLE
IPTorrents query fixes and improvements and add Peerflix download provider 

### PR DESCRIPTION
**Pull request by tsoernes**
Surrounding the movie title with quotes resulted in very few results on IPTorrents.
Removing the quotes and searching just for title instead of title and tags resulted in no false positives but much better results.
Improved movie quality to IPTorrent search category mapping.

Added [Peerflix](https://github.com/mafintosh/peerflix) torrent download provider for movie streaming.

### CODE REVIEW

**Comment by RuudBurger** [comment]
Can you make the PR against the develop branch?

**Comment by CDeLeon94** [comment]
I'd love to see the fix for IPT implemented.  
  
In the meantime, I will edit my files manually.

**Comment by tsoernes** [comment]
My fix is not working anymore. Try jackett

**Comment by kmr2319** [comment]
The IPTorrents related fixes were submitted and merged via PR #7158 - and they appear to be working as far as my testing goes.

I would recommend closing this PR per @tsoernes 's ["not working" comment](https://github.com/CouchPotato/CouchPotatoServer/pull/7023#issuecomment-260216766) and the fact that @RuudBurger requested this be submitted against the devlop branch.

Should perrflix changes still be desired, submit a new PR for those changed against the current develop branch.

Thanks @tsoernes for the original IPT changes!

**Pull request closed without merging**
