### PR TITLE
T411 provider

### PR DESCRIPTION
**Pull request by ibibah**
Add t411 provider.
I've try to respect the class model to do a good integration in your framework.
I 'm sure french guy's appreciate.

### CODE REVIEW

**Comment by ibibah** [comment]
closed because to big changes

**Comment by hadim** [comment]
t411 provider would be very nice ! Any news on this ?

**Comment by ibibah** [comment]
i maintained my own plugin at :
https://github.com/ibibah/CouchPotato-t411-ibibah_plugin.git

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-04-14 0:46 GMT+02:00 Hadrien Mary <notifications@github.com>:

**Comment by hadim** [comment]
@ibibah could you propose a pull request to add your plugin inside CouchPotatoServer ?

**Comment by ibibah** [comment]
i've try to do but this was refused. look at #6005

**Pull request closed without merging**
