### PR TITLE
Add FLV extension to movie scanner plugin.

### PR DESCRIPTION
**Pull request by sunsea**
Hi,
could you please add the FLV extension to the movie scanner as I have several movies in this format.
Thanks,
Ralph.

### CODE REVIEW

**Comment by RuudBurger** [comment]
Flash?

**Comment by sunsea** [comment]
Yes, I know it seems strange, but a lot of movies that are not well known (small productions) can be found in this format.

**Comment by RuudBurger** [comment]
Think it doesn't hurt anything if it marks a FLV as movie file.

**Comment by sunsea** [comment]
Thanks.

**Pull request merged**
