### PR TITLE
[TV] Make show support configurable

### PR DESCRIPTION
**Pull request by k0ekk0ek**
Show support is now configurable from the settings menu and marked as EXPERIMENTAL. If turned off, which is the default setting, no searches for shows will be done, also the main "Shows" tab won't be visible. Hopefully this will pave the path to the tv branch getting merged back into develop a little.

### CODE REVIEW

**Comment by jkaberg** [comment]
Nice to see someone picking this up again @k0ekk0ek , if you dont mind me asking - whats your long term plans for TV branch?

My plan was to get back to this, this summer but things just keeps stacking up

**Comment by k0ekk0ek** [comment]
@jkaberg My plan basically is to mark is as an experimental, disabled by default, feature first. Make sure we're not breaking existing functionality and get the tv branch merged to develop. That should make it easier to get provider creators to add support for shows and maybe require show support for new providers. It may also attract developers, once they see the feature is actually being worked on. Apart from that I'm also hoping to get people testing tv functionality. After the merge to develop, I'll be ironing out bugs that slipped by unseen and add the features needed to get to the point it's considered stable and more or less feature complete. After that I'll be adding requested and missing features.

**Comment by jkaberg** [comment]
Thats cool @k0ekk0ek, thanks for your reply

Perhaps @fuzeman @nrgaway would like to see this :-)

**Comment by fuzeman** [comment]
I'm happy to put some time into this again, maybe we should setup a [Gitter](https://gitter.im) or [Slack](https://slack.com/) channel to discuss things more?

**Comment by jkaberg** [comment]
I'd like an gitter chat. Thoughts @RuudBurger?
10. aug. 2015 10.59 skrev "Dean Gardiner" <notifications@github.com>:

**Comment by nrgaway** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 08/10/2015 04:59 AM, Dean Gardiner wrote:
> I'm happy to put some time into this again, maybe we should setup a [Gitter](https://gitter.im) or [Slack](https://slack.com/) channel to discuss things more? > > --- > Reply to this email directly or view it on GitHub: >
https://github.com/RuudBurger/CouchPotatoServer/pull/5192#issuecomment-129372562
Cool :)

I may have some more time as well; but not for about 4 weeks.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJVyH1MAAoJEELOese9Ajr6GYgP/0Fmvomg9tjcs9wu3fTlvmiq
hoEBgj9MREn3RAsg8TK6mKsej798I65nWknKvLpYOC96aawQw8QgxAzXVt9dNPDT
ADT3k2n4GkreWwPfbhSqtFfctb/VlPmey6hEE0n3h98OnwE7EjkW+MG7gqNphsix
vxHUJgBPC50v0k4I1wlv5/VKr6afTBAkZVzILE0I0T17ow/7RUhk006Sjas1otNO
dsG6YWX2KVryqn8a20sefCp4Ph6/33euwgqojvgacqG2ZgzuIauTHplucMSyixZp
pJknRrQZFck0dj9vmFgvvRV6q6ZNq5N+9rO/GBRr7B6Ri3ovN6RcDWk7bITlScHN
Q4KqgOx768radKhrui8LKDeYoXjb7yCHSA32hMu1KMadFYIii1sovgkhgj14JqUL
DGg3wpYikyfXFf5tL2eBCUZUBS8JwS7HrvLrDyUODBQVZZfIUstzzfVRcq8Be0Lo
HynQ7yHKYoRJ6eCjDi2obVaeaqQpJ8bVz85v69OwgbhONUXQsTDZ7rE0fV/jKxyE
ImtdiyKNpV9xE4/ut9OBpx620DzRR6++nu+WlPofz8KepYyzp/xnbxOQREYAtAps
WMxYe//lxpzBbHTxAg8DHe46gBVrsSzIr/hr0BQC+XQfe1s4pjbX1zargA7EOQNe
Un7O+pHQHC9MCrw1hjQm
=pGMi
-----END PGP SIGNATURE-----

**Comment by jkaberg** [comment]
https://github.com/RuudBurger/CouchPotatoServer/pull/5208

**Pull request merged**
