### PR TITLE
qbittorrent apiv2 (4.1+)

### PR DESCRIPTION
**Pull request by AnilDaoud**
api v1 deprecated in qbittorrent 4.2. this switches to apiv2 and breaks compatibility with qbittorrent v3

### CODE REVIEW

**Comment by Xx-Ness-xX** [comment]
When do we expect to have this fix merge into the master branch? My couchpotato hasn't been able to download anything for the past 2 weeks. Thanks

**Comment by Xx-Ness-xX** [comment]
I copied your client.py, now couchpotato will snatch the movies, but it does not set the label of the torrent.
Thanks,

**Comment by Xx-Ness-xX** [comment]
@RuudBurger do you think you can add this to the commit? I had it working with @AnilDaoud 's code, but the recent CP update has wiped those codes clean.
Thanks,

**Comment by fanboyfanboy** [comment]
would love to see this merged soon 👍🏽

**Comment by matthewcky2k** [comment]
Please merge as qbitorrent is currently broken

**Comment by Xx-Ness-xX** [comment]
@AnilDaoud 
I am running your fork right now, but I still couldn't get the download to work. I am not sure if it is still qbittorrent API related or not. here is the error logs:

**Edit: My mistake, I did not git clone right. It is all good now!**

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(CouchPotato:CouchPotatoServer master) 26306b3d (2020-02-16 00:32:45)
Running on: ...
### Logs:
```
02-28 11:58:49 INFO [tato.core.plugins.release] Tried to download, but the "torrent_magnet" downloader gave an error 
02-28 11:59:11 ERROR [chpotato.core.plugins.log] API log: {'file': u'https://HOST/cp/static/scripts/combined.plugins.min.js?1582322305', 'message': u"chrome 80: \nUncaught TypeError: Cannot read property 'length' of undefined", 'line': u'1288', 'page': u'https://HOST/cp/', '_request': <couchpotato.api.ApiHandler object at 0x0405BFF0>} 
```
Thanks,

**Comment by fanboyfanboy** [comment]
any update on when this might be merged?

**Comment by hannonq** [comment]
I'm also interested in know when/if this is going to be merged. Any news?

**Comment by r0bb10** [comment]
bump for the merge, works fine tested.

**Comment by Rotbot9k** [comment]
bump waiting for this fix on my freenas setup

**Comment by raylanser** [comment]
So this fixes connection issues when not enabling SSL for the qbittorrent webui, but with SSL enabled and url adjustments made in the downloader settings I still get the following error:

`[ couchpotato.api] Failed doing api request "download.qbittorrent.test": Traceback (most recent call last): File "/app/couchpotato/couchpotato/api.py", line 36, in run_handler res = api[route](**kwargs) File "/app/couchpotato/couchpotato/core/_base/downloader/main.py", line 179, in _test t = self.test() File "/app/couchpotato/couchpotato/core/downloaders/qbittorrent_.py", line 46, in test return self.connect() File "/app/couchpotato/couchpotato/core/downloaders/qbittorrent_.py", line 30, in connect self.qb.logout() File "/app/couchpotato/libs/qbittorrent/client.py", line 117, in logout response = self._get('auth/logout') File "/app/couchpotato/libs/qbittorrent/client.py", line 42, in _get return self._request(endpoint, 'get', **kwargs) File "/app/couchpotato/libs/qbittorrent/client.py", line 74, in _request request = rq.get(final_url, **kwargs) File "/app/couchpotato/libs/requests/sessions.py", line 481, in get return self.request('GET', url, **kwargs) File "/app/couchpotato/libs/requests/sessions.py", line 469, in request resp = self.send(prep, **send_kwargs) File "/app/couchpotato/libs/requests/sessions.py", line 577, in send r = adapter.send(request, **kwargs) File "/app/couchpotato/libs/requests/adapters.py", line 413, in send raise ConnectionError(err, request=request) ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))`

Is there a related API change issue?

**Pull request merged**
