### PR TITLE
Add RARBG to torrent providers

### PR DESCRIPTION
**Pull request by fernandog**
- Make sure your pull request is made for the develop branch (or relevant feature branch). DONE
- Have you tested your PR? If not, why? Yes
- Does your PR have any limitations I should know of? No
- Is your PR up-to-date with the branch you're trying to push into? Yes

coded by @KrunchMuffin 

discussion and tests started here: https://github.com/rarbg/torrentapi/issues/1#issuecomment-114180256

### CODE REVIEW

**Comment by KrunchMuffin** [comment]
Thanks @fernandog. would really like to know what I was doing wrong so I can figure it out if there is a next time.

**Comment by fernandog** [comment]
@RuudBurger is this OK? I've been used RARBG as the only provider for a few days. No issues/errors. Snatched ok
In SR, rarbg work flawlessly.

**Comment by furieuxjk** [comment]
I can confirm that this works like a charm! :+1:

**Comment by RuudBurger** [comment]
Cool, thanks for the code!

**Comment by fernandog** [comment]
@KrunchMuffin can you check this out please?



shouldn't be quality WEB-DL?

```
        # SOURCE #
        source = 'HD-Rip'            
        s = re.search("(?i)(WEB-DL|WEB_DL|WEB\.DL)", filename)
        if s:
            source = 'WEB-DL'
        s = re.search("(?i)(BRRIP|BDRIP|BluRay)", filename)
        if s:
            source = 'BR-Rip'
```

**Comment by KrunchMuffin** [comment]
I don't even use the SOURCE var in that. CP handles that itself.

**Comment by mano3m** [comment]
Web-dl is not a native quality of CPS. These types are found 'medium' quality are all lumped in br-rip, so the result is as expected.

**Pull request merged**
