### PR TITLE
Added YTS Popular Automation.

### PR DESCRIPTION
**Pull request by rhyswilliamsza**
### Description of what this fixes:
**_NEW FEATURE_**
YTS Popular-Downloads grabbing: Added YTS automation provider, pulling popular-downloads directly from their site. Will safely and automatically fail if website unavailable or layout changes.

### CODE REVIEW

**Comment by rhyswilliamsza** [comment]
Requires HTML parser module. This is included by default with Python 2.7+. Unsure why travis couldn't find the library.

**Comment by nydave69** [comment]
2 questions, 
1.  how does one add this to the current master that I'm running..
2. Could this be done for RARBG..

**Comment by rhyswilliamsza** [comment]
I can quickly write a RARBG version if you'd like @nydave69?

**Comment by nydave69** [comment]
That would be great, since i see them releasing a lot of new things.
merge it with master...

**Pull request merged**
