### PR TITLE
add extratorrent provider to /couchpotato/core/media/movie/providers/torrent/

### PR DESCRIPTION
**Pull request by NULLx76**
### Description of what this fixes:
Added extratorrent provider

### CODE REVIEW

**Comment by MrHillard** [comment]
I've applied this and can confirm it's added extratorrent in the menu, unfortunately couchpotato doesn't seem to use it at all.
When it's added as the only Searcher I get:
ERROR[core.media._base.searcher] There aren't any providers enabled for your downloader (torrent,torrent_magnet). Check your settings.
Then if I select another Searcher, I can see from the logs it's that second one only.
Adding a 500 Extra Score to tExtratorrent didn't make a difference.
Running 40577904.

**Comment by lloydie2009** [comment]
I also second MrHillard's comments.

It's added a searcher within the Couch Potato menu, however when searching for something i don't see it flag up anywhere within my debug logging, still only rarbg.

**Comment by ward0** [comment]
I have this .py file in location(synology) /var/packages/couchpotatoserver-custom/target/var/CouchPotatoServer/couchpotato/core/media/_base/providers/torrent 

Rebooted CP but it doesn't work? Also not seeing in searcher .. am i doing something wrong pls?

**Comment by RuudBurger** [comment]
You need to add the provider to https://github.com/victorheld/CouchPotatoServer/tree/develop/couchpotato/core/media/movie/providers/torrent and link to the base provider.

**Comment by victorheld** [comment]
Added the provider to /couchpotato/core/media/movie/providers/torrent/

 in commit c34680b15cbb7bc88d600067a72cd0c027c24c00

**Comment by MrHillard** [comment]
after adding the provider to /couchpotato/core/media/movie/providers/torrent/ I now get:
[ders.torrent.extratorrent] Failed parsing results from ExtraTorrent: Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/media/_base/providers/torrent/extratorrent.py", line 61, in _searchOnTitle torrents_total = tryFloat(matches.group(1)) AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ward0** [comment]
Thanks @RuudBurger  and @victorheld  i will test again.

**Comment by ward0** [comment]
Is this the same provider? https://github.com/msgprado/couchpotato.provider.extratorrent 

it still doesn't work for me :( 

 @RuudBurger  how to add to the baseprovider pls?

**Pull request closed without merging**
