### PR TITLE
Add t411 provider

### PR DESCRIPTION
**Pull request by ibibah**
Add t411 provider :
- Using t411 api
- Trying to respect couchpotato class model.

### CODE REVIEW

**Comment by RuudBurger** [comment]
I won't add French only provider, sorry.
You can add it to your custom_plugin folder (which you can find in your data directory) though.

**Comment by duramato** [comment]
@RuudBurger T411 inst a french only provider i use it all the time to get scene releases...

**Comment by RuudBurger** [comment]
The site is and looking by the categories a lot of mixed content, which will lead to lots of false positives.

**Comment by hadim** [comment]
@RuudBurger don't you think that it could be disable by default ? We can also add a warning message saying that this provider mostly have french content.

**Comment by hadim** [comment]
What a shame...

**Comment by kwaio** [comment]
Agreed, that's a shame. provinding that kind of content-rich providers, despite being mainly non-english (although a lot of soft-subbed english items) would help a lot of users. that's the kind of reasons I don't use CP anymore =/

**Pull request closed without merging**
